Areas/EmployeesArea/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab01ASPWebApp.ContextDB;
using lab01ASPWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace lab01ASPWebApp.Areas.EmployeesArea.Controllers
{
    [AllowAnonymous]// default , allows any one to access the employees arera 
    [Area("EmployeesArea")]
    public class EmployeesController : Controller
    {
        private readonly AppDBContext _context;

        public EmployeesController(AppDBContext context)
        {
            _context = context;
        }

        // GET: EmployeesArea/Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.employees.ToListAsync());
        }

        // GET: EmployeesArea/Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: EmployeesArea/Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EmployeesArea/Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Phone,Age,Salary")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: EmployeesArea/Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: EmployeesArea/Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Phone,Age,Salary")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: EmployeesArea/Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: EmployeesArea/Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.employees.FindAsync(id);
            if (employee != null)
            {
                _context.employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.employees.Any(e => e.Id == id);
        }
    }
}

Controllers/CategoryController.cs
using lab01ASPWebApp.Models;
using lab01ASPWebApp.Repo.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

namespace lab01ASPWebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private IRepo<Category> _repo;



        public CategoryController(IRepo<Category> repo) 
        {
            _repo = repo;
        }



        public IActionResult Index()
        {
            return View(_repo.GetAll());
        }




        // اللي فوق هو هو اللي تحت بس اللي تحت اسرع 
        //public async Task<IActionResult> Index() // async here , i have to write the return type between 'Task<>'
        //{
        //    var SingleCategory = _repo.GetOne(x=>x.Name == "computer"); // to search for a computer . -- whats the use of this then ?
        //    var AllCategories =  await _repo.GetAllAsync("Items"); // i have to write 'await' here 
        //    return  View(AllCategories); 
        //}





        //public IActionResult create()
        //{
        //    return View(_repo.GetAll());
        //}
        //public async Task<IActionResult>  createAsync()
        //{
        //    return View(await _repo.GetAllAsync()); // i have to write 'await' here
        //}


        //Get 
        public IActionResult Create()
        {
            return View();
        }


        //  POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category) 
        {
            if (!ModelState.IsValid ) 
            {
                return View(category);
            }
            _repo.AddSingle(category);
            return RedirectToAction("Index");
        }


        //Get
        public IActionResult Edit(int? id)
        {
            if (id == null||id==0)
            {
                return NotFound();
            }
            var category = _repo.GetById(id.Value);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //  POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            _repo.UpdateSingle(category);
            return RedirectToAction("Index");
        }



        //Get
        public IActionResult Delete(int? id)
        {

            if (id == null|| id==0)
            {
                return NotFound();
            }
            var category = _repo.GetById(id.Value);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //  POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category category)
        {
           
            _repo.DeleteSingle(category);
            return RedirectToAction("Index");
        }




    }
}

Controllers/ItemController.cs
using lab01ASPWebApp.ContextDB;
using lab01ASPWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace lab01ASPWebApp.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {


        private readonly AppDBContext dbContext;// dependancy injection 


        public ItemController(AppDBContext dp)
        {
            dbContext = dp;
        }



        public IActionResult Index()
        {
            IEnumerable<Items> ItemList = dbContext.items.Include(x => x.Category).ToList();// to add and store my items on the page to a list with type 'IEnumerable<Items>'
                                                                                            // here the items will also include the items in the categories table
            return View(ItemList);
        }



        public void SelectItemList(int? id=1) // if the user doesnt choose a category the dafaylt will be 0
        {
            //List<Category> categories = new List<Category>()
            //{
            // new Category { Id =1 ,Name="select"}
            // , new Category { Id =2 ,Name="mobile"}
            // , new Category { Id =3 ,Name="computer"}
            // , new Category { Id =4 ,Name="tablet"}

            //}; // creating the category list
            List<Category> categories = dbContext.categories.ToList();
            SelectList list =new SelectList(categories , "Id", "Name", id); //represents a list that lets its users select a single item (from html<select>) with the specified collection odf the SelectItemList objects
            ViewBag.CategoryList = list;
        }


        //GET
        public IActionResult Create()
        {
            SelectItemList();
            return View();
        }



        //POST -- sets value to the database and posts it on the website 
        [HttpPost] // used to post the solution on the site
        public IActionResult Create(Items item)
        {


            //if (item.Name.ToLower() == "ahmed") //to create a custom error , tolower() is used to make al the latters entered in lower case , to avoid tricks :)
            if (item.Name == "ahmed")  // but it causes errors so we will avoid it :(
            {
                ModelState.AddModelError("custom error", "name cannot be ahmed !!!");  // creating the custom error
            }



            if (!ModelState.IsValid)
            {
                return View(item);  //if the user enters a non-valid input , the page will reload with the same data and no actions will be done
            }



            dbContext.items.Add(item);   // to add items to db
            dbContext.SaveChanges();     //to save changes to db
            TempData["Success"] = "Item Created Successfully";
            return RedirectToAction("Index"); // will go to the method Index in the 17th line here and pass its values to it .
        }





        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



        //GET
        public IActionResult Edit(int? Id)
        {
            if (Id == 0 || Id == null)
            {
                return NotFound(); // returns ERROR 404 if there is no id 
            }
            var item = dbContext.items.Find(Id); // to find the id in the list in the db 
            if (item == null)
            {
                return NotFound(); // returns ERROR 404 if there is no elements 
            }
            SelectItemList(item.CategoryId);
            return View(item);
        }



        //POST -- sets value to the database and posts it on the website 
        [HttpPost] // used to post the solution on the site
        public IActionResult Edit(Items item)
        {


            //if (item.Name.ToLower() == "ahmed") //to create a custom error , tolower() is used to make al the latters entered in lower case , to avoid tricks :)
            if (item.Name == "ahmed")  // but it causes errors so we will avoid it :(
            {
                ModelState.AddModelError("custom error", "name cannot be ahmed !!!");  // creating the custom error
            }



            if (!ModelState.IsValid)
            {
                return View(item);  //if the user enters a non-valid input , the page will reload with the same data and no actions will be done
            }



            dbContext.items.Update(item);   // to update items to db
            dbContext.SaveChanges();     //to save changes to db
            TempData["Successs"] = "Item Edited Successfully";
            return RedirectToAction("Index"); // will go to the method Index in the 17th line here and pass its values to it .
        }




        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        //GET
        public IActionResult Delete(int? Id)
        {
            return View();  
        }



        //POST -- sets value to the database and posts it on the website 
        [HttpPost] // used to post the solution on the site
        public IActionResult Delete(Items item)
        { 
            dbContext.items.Remove(item);   // to delete items in db
            dbContext.SaveChanges();     //to save changes to db

            return RedirectToAction("Index"); // will go to the method Index in the 17th line here and pass its values to it .
        }


    }
}

Views/Shared/_Alerts.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success" role="alert" id="message">
        @TempData["Success"]
    </div>
}
@if (TempData["Successs"] != null)
{
    <div class="alert alert-success" role="alert" id="message">
        @TempData["Successs"]
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab01ASPWebApp</title>
    <link rel="stylesheet" href="~/css/MorphStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab01ASPWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab01ASPWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Dont Click Here</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="EmployeesArea" asp-controller="Employees" asp-action="Index">employee list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Category" asp-action="Index">category list</a>
                        </li>
                        
                    </ul>

                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - lab01ASPWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>